/*
 * Actions Owl2X SoCs pinctrl driver.
 *
 * Copyright (C) 2014
 *
 * B. Mouritsen <bnmguy@gmail.com>
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2.  This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#ifndef __PINCTRL_OWL2X_H
#define __PINCTRL_OWLX_H

#include <linux/kernel.h>
#include <linux/spinlock.h>

#define GPIOA_OUTPUT_BASE  0
#define GPIOA_INPUT_BASE   32
#define GPIOA_DAT_BASE     64
#define GPIOB_OUTPUT_BASE  96
#define GPIOB_INPUT_BASE   128
#define GPIOB_DAT_BASE     160
#define GPIOC_OUTPUT_BASE  192
#define GPIOC_INPUT_BASE   224
#define GPIOC_DAT_BASE     256
#define GPIOD_OUTPUT_BASE  288
#define GPIOD_INPUT_BASE   320
#define GPIOD_DAT_BASE     352
#define GPIOE_OUTPUT_BASE  384
#define GPIOE_INPUT_BASE   416
#define GPIOE_DAT_BASE     448

#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA0    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 0, "GPIOA0")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA1    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 1, "GPIOA1")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA2    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 2, "GPIOA2")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA3    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 3, "GPIOA3")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA4    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 4, "GPIOA4")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA5    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 5, "GPIOA5")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA6    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 6, "GPIOA6")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA7    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 7, "GPIOA7")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA8    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 8, "GPIOA8")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA9    PINCTRL_PIN(GPIOA_OUTPUT_BASE + 9, "GPIOA9")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA10   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 10, "GPIOA10")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA11   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 11, "GPIOA11")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA12   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 12, "GPIOA12")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA13   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 13, "GPIOA13")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA14   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 14, "GPIOA14")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA15   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 15, "GPIOA15")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA16   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 16, "GPIOA16")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA17   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 17, "GPIOA17")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA18   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 18, "GPIOA18")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA19   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 19, "GPIOA19")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA20   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 20, "GPIOA20")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA21   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 21, "GPIOA21")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA22   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 22, "GPIOA22")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA23   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 23, "GPIOA23")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA24   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 24, "GPIOA24")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA25   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 25, "GPIOA25")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA26   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 26, "GPIOA26")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA27   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 27, "GPIOA27")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA28   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 28, "GPIOA28")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA29   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 29, "GPIOA29")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA30   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 30, "GPIOA30")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOA31   PINCTRL_PIN(GPIOA_OUTPUT_BASE + 31, "GPIOA31")

#define OWL2X_PINCTRL_PIN_INPUT_GPIOA0     PINCTRL_PIN(GPIOA_INPUT_BASE + 0, "GPIOA0")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA1     PINCTRL_PIN(GPIOA_INPUT_BASE + 1, "GPIOA1")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA2     PINCTRL_PIN(GPIOA_INPUT_BASE + 2, "GPIOA2")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA3     PINCTRL_PIN(GPIOA_INPUT_BASE + 3, "GPIOA3")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA4     PINCTRL_PIN(GPIOA_INPUT_BASE + 4, "GPIOA4")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA5     PINCTRL_PIN(GPIOA_INPUT_BASE + 5, "GPIOA5")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA6     PINCTRL_PIN(GPIOA_INPUT_BASE + 6, "GPIOA6")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA7     PINCTRL_PIN(GPIOA_INPUT_BASE + 7, "GPIOA7")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA8     PINCTRL_PIN(GPIOA_INPUT_BASE + 8, "GPIOA8")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA9     PINCTRL_PIN(GPIOA_INPUT_BASE + 9, "GPIOA9")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA10    PINCTRL_PIN(GPIOA_INPUT_BASE + 10, "GPIOA10")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA11    PINCTRL_PIN(GPIOA_INPUT_BASE + 11, "GPIOA11")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA12    PINCTRL_PIN(GPIOA_INPUT_BASE + 12, "GPIOA12")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA13    PINCTRL_PIN(GPIOA_INPUT_BASE + 13, "GPIOA13")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA14    PINCTRL_PIN(GPIOA_INPUT_BASE + 14, "GPIOA14")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA15    PINCTRL_PIN(GPIOA_INPUT_BASE + 15, "GPIOA15")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA16    PINCTRL_PIN(GPIOA_INPUT_BASE + 16, "GPIOA16")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA17    PINCTRL_PIN(GPIOA_INPUT_BASE + 17, "GPIOA17")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA18    PINCTRL_PIN(GPIOA_INPUT_BASE + 18, "GPIOA18")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA19    PINCTRL_PIN(GPIOA_INPUT_BASE + 19, "GPIOA19")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA20    PINCTRL_PIN(GPIOA_INPUT_BASE + 20, "GPIOA20")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA21    PINCTRL_PIN(GPIOA_INPUT_BASE + 21, "GPIOA21")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA22    PINCTRL_PIN(GPIOA_INPUT_BASE + 22, "GPIOA22")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA23    PINCTRL_PIN(GPIOA_INPUT_BASE + 23, "GPIOA23")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA24    PINCTRL_PIN(GPIOA_INPUT_BASE + 24, "GPIOA24")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA25    PINCTRL_PIN(GPIOA_INPUT_BASE + 25, "GPIOA25")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA26    PINCTRL_PIN(GPIOA_INPUT_BASE + 26, "GPIOA26")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA27    PINCTRL_PIN(GPIOA_INPUT_BASE + 27, "GPIOA27")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA28    PINCTRL_PIN(GPIOA_INPUT_BASE + 28, "GPIOA28")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA29    PINCTRL_PIN(GPIOA_INPUT_BASE + 29, "GPIOA29")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA30    PINCTRL_PIN(GPIOA_INPUT_BASE + 30, "GPIOA30")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOA31    PINCTRL_PIN(GPIOA_INPUT_BASE + 31, "GPIOA31")

#define OWL2X_PINCTRL_PIN_DAT_GPIOA0     PINCTRL_PIN(GPIOA_DAT_BASE + 0, "GPIOA0")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA1     PINCTRL_PIN(GPIOA_DAT_BASE + 1, "GPIOA1")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA2     PINCTRL_PIN(GPIOA_DAT_BASE + 2, "GPIOA2")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA3     PINCTRL_PIN(GPIOA_DAT_BASE + 3, "GPIOA3")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA4     PINCTRL_PIN(GPIOA_DAT_BASE + 4, "GPIOA4")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA5     PINCTRL_PIN(GPIOA_DAT_BASE + 5, "GPIOA5")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA6     PINCTRL_PIN(GPIOA_DAT_BASE + 6, "GPIOA6")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA7     PINCTRL_PIN(GPIOA_DAT_BASE + 7, "GPIOA7")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA8     PINCTRL_PIN(GPIOA_DAT_BASE + 8, "GPIOA8")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA9     PINCTRL_PIN(GPIOA_DAT_BASE + 9, "GPIOA9")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA10    PINCTRL_PIN(GPIOA_DAT_BASE + 10, "GPIOA10")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA11    PINCTRL_PIN(GPIOA_DAT_BASE + 11, "GPIOA11")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA12    PINCTRL_PIN(GPIOA_DAT_BASE + 12, "GPIOA12")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA13    PINCTRL_PIN(GPIOA_DAT_BASE + 13, "GPIOA13")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA14    PINCTRL_PIN(GPIOA_DAT_BASE + 14, "GPIOA14")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA15    PINCTRL_PIN(GPIOA_DAT_BASE + 15, "GPIOA15")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA16    PINCTRL_PIN(GPIOA_DAT_BASE + 16, "GPIOA16")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA17    PINCTRL_PIN(GPIOA_DAT_BASE + 17, "GPIOA17")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA18    PINCTRL_PIN(GPIOA_DAT_BASE + 18, "GPIOA18")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA19    PINCTRL_PIN(GPIOA_DAT_BASE + 19, "GPIOA19")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA20    PINCTRL_PIN(GPIOA_DAT_BASE + 20, "GPIOA20")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA21    PINCTRL_PIN(GPIOA_DAT_BASE + 21, "GPIOA21")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA22    PINCTRL_PIN(GPIOA_DAT_BASE + 22, "GPIOA22")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA23    PINCTRL_PIN(GPIOA_DAT_BASE + 23, "GPIOA23")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA24    PINCTRL_PIN(GPIOA_DAT_BASE + 24, "GPIOA24")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA25    PINCTRL_PIN(GPIOA_DAT_BASE + 25, "GPIOA25")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA26    PINCTRL_PIN(GPIOA_DAT_BASE + 26, "GPIOA26")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA27    PINCTRL_PIN(GPIOA_DAT_BASE + 27, "GPIOA27")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA28    PINCTRL_PIN(GPIOA_DAT_BASE + 28, "GPIOA28")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA29    PINCTRL_PIN(GPIOA_DAT_BASE + 29, "GPIOA29")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA30    PINCTRL_PIN(GPIOA_DAT_BASE + 30, "GPIOA30")
#define OWL2X_PINCTRL_PIN_DAT_GPIOA31    PINCTRL_PIN(GPIOA_DAT_BASE + 31, "GPIOA31")

#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB0    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 0, "GPIOB0")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB1    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 1, "GPIOB1")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB2    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 2, "GPIOB2")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB3    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 3, "GPIOB3")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB4    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 4, "GPIOB4")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB5    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 5, "GPIOB5")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB6    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 6, "GPIOB6")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB7    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 7, "GPIOB7")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB8    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 8, "GPIOB8")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB9    PINCTRL_PIN(GPIOB_OUTPUT_BASE + 9, "GPIOB9")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB10   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 10, "GPIOB10")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB11   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 11, "GPIOB11")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB12   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 12, "GPIOB12")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB13   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 13, "GPIOB13")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB14   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 14, "GPIOB14")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB15   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 15, "GPIOB15")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB16   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 16, "GPIOB16")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB17   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 17, "GPIOB17")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB18   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 18, "GPIOB18")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB19   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 19, "GPIOB19")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB20   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 20, "GPIOB20")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB21   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 21, "GPIOB21")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB22   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 22, "GPIOB22")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB23   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 23, "GPIOB23")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB24   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 24, "GPIOB24")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB25   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 25, "GPIOB25")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB26   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 26, "GPIOB26")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB27   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 27, "GPIOB27")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB28   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 28, "GPIOB28")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB29   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 29, "GPIOB29")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB30   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 30, "GPIOB30")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOB31   PINCTRL_PIN(GPIOB_OUTPUT_BASE + 31, "GPIOB31")

#define OWL2X_PINCTRL_PIN_INPUT_GPIOB0     PINCTRL_PIN(GPIOB_INPUT_BASE + 0, "GPIOB0")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB1     PINCTRL_PIN(GPIOB_INPUT_BASE + 1, "GPIOB1")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB2     PINCTRL_PIN(GPIOB_INPUT_BASE + 2, "GPIOB2")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB3     PINCTRL_PIN(GPIOB_INPUT_BASE + 3, "GPIOB3")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB4     PINCTRL_PIN(GPIOB_INPUT_BASE + 4, "GPIOB4")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB5     PINCTRL_PIN(GPIOB_INPUT_BASE + 5, "GPIOB5")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB6     PINCTRL_PIN(GPIOB_INPUT_BASE + 6, "GPIOB6")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB7     PINCTRL_PIN(GPIOB_INPUT_BASE + 7, "GPIOB7")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB8     PINCTRL_PIN(GPIOB_INPUT_BASE + 8, "GPIOB8")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB9     PINCTRL_PIN(GPIOB_INPUT_BASE + 9, "GPIOB9")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB10    PINCTRL_PIN(GPIOB_INPUT_BASE + 10, "GPIOB10")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB11    PINCTRL_PIN(GPIOB_INPUT_BASE + 11, "GPIOB11")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB12    PINCTRL_PIN(GPIOB_INPUT_BASE + 12, "GPIOB12")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB13    PINCTRL_PIN(GPIOB_INPUT_BASE + 13, "GPIOB13")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB14    PINCTRL_PIN(GPIOB_INPUT_BASE + 14, "GPIOB14")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB15    PINCTRL_PIN(GPIOB_INPUT_BASE + 15, "GPIOB15")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB16    PINCTRL_PIN(GPIOB_INPUT_BASE + 16, "GPIOB16")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB17    PINCTRL_PIN(GPIOB_INPUT_BASE + 17, "GPIOB17")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB18    PINCTRL_PIN(GPIOB_INPUT_BASE + 18, "GPIOB18")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB19    PINCTRL_PIN(GPIOB_INPUT_BASE + 19, "GPIOB19")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB20    PINCTRL_PIN(GPIOB_INPUT_BASE + 20, "GPIOB20")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB21    PINCTRL_PIN(GPIOB_INPUT_BASE + 21, "GPIOB21")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB22    PINCTRL_PIN(GPIOB_INPUT_BASE + 22, "GPIOB22")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB23    PINCTRL_PIN(GPIOB_INPUT_BASE + 23, "GPIOB23")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB24    PINCTRL_PIN(GPIOB_INPUT_BASE + 24, "GPIOB24")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB25    PINCTRL_PIN(GPIOB_INPUT_BASE + 25, "GPIOB25")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB26    PINCTRL_PIN(GPIOB_INPUT_BASE + 26, "GPIOB26")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB27    PINCTRL_PIN(GPIOB_INPUT_BASE + 27, "GPIOB27")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB28    PINCTRL_PIN(GPIOB_INPUT_BASE + 28, "GPIOB28")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB29    PINCTRL_PIN(GPIOB_INPUT_BASE + 29, "GPIOB29")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB30    PINCTRL_PIN(GPIOB_INPUT_BASE + 30, "GPIOB30")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOB31    PINCTRL_PIN(GPIOB_INPUT_BASE + 31, "GPIOB31")

#define OWL2X_PINCTRL_PIN_DAT_GPIOB0     PINCTRL_PIN(GPIOB_DAT_BASE + 0, "GPIOB0")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB1     PINCTRL_PIN(GPIOB_DAT_BASE + 1, "GPIOB1")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB2     PINCTRL_PIN(GPIOB_DAT_BASE + 2, "GPIOB2")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB3     PINCTRL_PIN(GPIOB_DAT_BASE + 3, "GPIOB3")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB4     PINCTRL_PIN(GPIOB_DAT_BASE + 4, "GPIOB4")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB5     PINCTRL_PIN(GPIOB_DAT_BASE + 5, "GPIOB5")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB6     PINCTRL_PIN(GPIOB_DAT_BASE + 6, "GPIOB6")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB7     PINCTRL_PIN(GPIOB_DAT_BASE + 7, "GPIOB7")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB8     PINCTRL_PIN(GPIOB_DAT_BASE + 8, "GPIOB8")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB9     PINCTRL_PIN(GPIOB_DAT_BASE + 9, "GPIOB9")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB10    PINCTRL_PIN(GPIOB_DAT_BASE + 10, "GPIOB10")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB11    PINCTRL_PIN(GPIOB_DAT_BASE + 11, "GPIOB11")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB12    PINCTRL_PIN(GPIOB_DAT_BASE + 12, "GPIOB12")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB13    PINCTRL_PIN(GPIOB_DAT_BASE + 13, "GPIOB13")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB14    PINCTRL_PIN(GPIOB_DAT_BASE + 14, "GPIOB14")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB15    PINCTRL_PIN(GPIOB_DAT_BASE + 15, "GPIOB15")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB16    PINCTRL_PIN(GPIOB_DAT_BASE + 16, "GPIOB16")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB17    PINCTRL_PIN(GPIOB_DAT_BASE + 17, "GPIOB17")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB18    PINCTRL_PIN(GPIOB_DAT_BASE + 18, "GPIOB18")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB19    PINCTRL_PIN(GPIOB_DAT_BASE + 19, "GPIOB19")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB20    PINCTRL_PIN(GPIOB_DAT_BASE + 20, "GPIOB20")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB21    PINCTRL_PIN(GPIOB_DAT_BASE + 21, "GPIOB21")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB22    PINCTRL_PIN(GPIOB_DAT_BASE + 22, "GPIOB22")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB23    PINCTRL_PIN(GPIOB_DAT_BASE + 23, "GPIOB23")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB24    PINCTRL_PIN(GPIOB_DAT_BASE + 24, "GPIOB24")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB25    PINCTRL_PIN(GPIOB_DAT_BASE + 25, "GPIOB25")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB26    PINCTRL_PIN(GPIOB_DAT_BASE + 26, "GPIOB26")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB27    PINCTRL_PIN(GPIOB_DAT_BASE + 27, "GPIOB27")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB28    PINCTRL_PIN(GPIOB_DAT_BASE + 28, "GPIOB28")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB29    PINCTRL_PIN(GPIOB_DAT_BASE + 29, "GPIOB29")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB30    PINCTRL_PIN(GPIOB_DAT_BASE + 30, "GPIOB30")
#define OWL2X_PINCTRL_PIN_DAT_GPIOB31    PINCTRL_PIN(GPIOB_DAT_BASE + 31, "GPIOB31")

#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC0    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 0, "GPIOC0")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC1    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 1, "GPIOC1")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC2    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 2, "GPIOC2")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC3    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 3, "GPIOC3")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC4    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 4, "GPIOC4")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC5    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 5, "GPIOC5")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC6    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 6, "GPIOC6")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC7    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 7, "GPIOC7")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC8    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 8, "GPIOC8")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC9    PINCTRL_PIN(GPIOC_OUTPUT_BASE + 9, "GPIOC9")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC10   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 10, "GPIOC10")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC11   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 11, "GPIOC11")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC12   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 12, "GPIOC12")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC13   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 13, "GPIOC13")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC14   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 14, "GPIOC14")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC15   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 15, "GPIOC15")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC16   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 16, "GPIOC16")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC17   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 17, "GPIOC17")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC18   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 18, "GPIOC18")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC19   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 19, "GPIOC19")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC20   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 20, "GPIOC20")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC21   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 21, "GPIOC21")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC22   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 22, "GPIOC22")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC23   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 23, "GPIOC23")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC24   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 24, "GPIOC24")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC25   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 25, "GPIOC25")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC26   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 26, "GPIOC26")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC27   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 27, "GPIOC27")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC28   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 28, "GPIOC28")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC29   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 29, "GPIOC29")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC30   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 30, "GPIOC30")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOC31   PINCTRL_PIN(GPIOC_OUTPUT_BASE + 31, "GPIOC31")

#define OWL2X_PINCTRL_PIN_INPUT_GPIOC0     PINCTRL_PIN(GPIOC_INPUT_BASE + 0, "GPIOC0")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC1     PINCTRL_PIN(GPIOC_INPUT_BASE + 1, "GPIOC1")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC2     PINCTRL_PIN(GPIOC_INPUT_BASE + 2, "GPIOC2")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC3     PINCTRL_PIN(GPIOC_INPUT_BASE + 3, "GPIOC3")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC4     PINCTRL_PIN(GPIOC_INPUT_BASE + 4, "GPIOC4")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC5     PINCTRL_PIN(GPIOC_INPUT_BASE + 5, "GPIOC5")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC6     PINCTRL_PIN(GPIOC_INPUT_BASE + 6, "GPIOC6")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC7     PINCTRL_PIN(GPIOC_INPUT_BASE + 7, "GPIOC7")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC8     PINCTRL_PIN(GPIOC_INPUT_BASE + 8, "GPIOC8")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC9     PINCTRL_PIN(GPIOC_INPUT_BASE + 9, "GPIOC9")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC10    PINCTRL_PIN(GPIOC_INPUT_BASE + 10, "GPIOC10")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC11    PINCTRL_PIN(GPIOC_INPUT_BASE + 11, "GPIOC11")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC12    PINCTRL_PIN(GPIOC_INPUT_BASE + 12, "GPIOC12")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC13    PINCTRL_PIN(GPIOC_INPUT_BASE + 13, "GPIOC13")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC14    PINCTRL_PIN(GPIOC_INPUT_BASE + 14, "GPIOC14")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC15    PINCTRL_PIN(GPIOC_INPUT_BASE + 15, "GPIOC15")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC16    PINCTRL_PIN(GPIOC_INPUT_BASE + 16, "GPIOC16")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC17    PINCTRL_PIN(GPIOC_INPUT_BASE + 17, "GPIOC17")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC18    PINCTRL_PIN(GPIOC_INPUT_BASE + 18, "GPIOC18")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC19    PINCTRL_PIN(GPIOC_INPUT_BASE + 19, "GPIOC19")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC20    PINCTRL_PIN(GPIOC_INPUT_BASE + 20, "GPIOC20")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC21    PINCTRL_PIN(GPIOC_INPUT_BASE + 21, "GPIOC21")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC22    PINCTRL_PIN(GPIOC_INPUT_BASE + 22, "GPIOC22")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC23    PINCTRL_PIN(GPIOC_INPUT_BASE + 23, "GPIOC23")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC24    PINCTRL_PIN(GPIOC_INPUT_BASE + 24, "GPIOC24")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC25    PINCTRL_PIN(GPIOC_INPUT_BASE + 25, "GPIOC25")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC26    PINCTRL_PIN(GPIOC_INPUT_BASE + 26, "GPIOC26")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC27    PINCTRL_PIN(GPIOC_INPUT_BASE + 27, "GPIOC27")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC28    PINCTRL_PIN(GPIOC_INPUT_BASE + 28, "GPIOC28")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC29    PINCTRL_PIN(GPIOC_INPUT_BASE + 29, "GPIOC29")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC30    PINCTRL_PIN(GPIOC_INPUT_BASE + 30, "GPIOC30")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOC31    PINCTRL_PIN(GPIOC_INPUT_BASE + 31, "GPIOC31")

#define OWL2X_PINCTRL_PIN_DAT_GPIOC0     PINCTRL_PIN(GPIOC_DAT_BASE + 0, "GPIOC0")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC1     PINCTRL_PIN(GPIOC_DAT_BASE + 1, "GPIOC1")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC2     PINCTRL_PIN(GPIOC_DAT_BASE + 2, "GPIOC2")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC3     PINCTRL_PIN(GPIOC_DAT_BASE + 3, "GPIOC3")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC4     PINCTRL_PIN(GPIOC_DAT_BASE + 4, "GPIOC4")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC5     PINCTRL_PIN(GPIOC_DAT_BASE + 5, "GPIOC5")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC6     PINCTRL_PIN(GPIOC_DAT_BASE + 6, "GPIOC6")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC7     PINCTRL_PIN(GPIOC_DAT_BASE + 7, "GPIOC7")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC8     PINCTRL_PIN(GPIOC_DAT_BASE + 8, "GPIOC8")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC9     PINCTRL_PIN(GPIOC_DAT_BASE + 9, "GPIOC9")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC10    PINCTRL_PIN(GPIOC_DAT_BASE + 10, "GPIOC10")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC11    PINCTRL_PIN(GPIOC_DAT_BASE + 11, "GPIOC11")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC12    PINCTRL_PIN(GPIOC_DAT_BASE + 12, "GPIOC12")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC13    PINCTRL_PIN(GPIOC_DAT_BASE + 13, "GPIOC13")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC14    PINCTRL_PIN(GPIOC_DAT_BASE + 14, "GPIOC14")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC15    PINCTRL_PIN(GPIOC_DAT_BASE + 15, "GPIOC15")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC16    PINCTRL_PIN(GPIOC_DAT_BASE + 16, "GPIOC16")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC17    PINCTRL_PIN(GPIOC_DAT_BASE + 17, "GPIOC17")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC18    PINCTRL_PIN(GPIOC_DAT_BASE + 18, "GPIOC18")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC19    PINCTRL_PIN(GPIOC_DAT_BASE + 19, "GPIOC19")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC20    PINCTRL_PIN(GPIOC_DAT_BASE + 20, "GPIOC20")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC21    PINCTRL_PIN(GPIOC_DAT_BASE + 21, "GPIOC21")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC22    PINCTRL_PIN(GPIOC_DAT_BASE + 22, "GPIOC22")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC23    PINCTRL_PIN(GPIOC_DAT_BASE + 23, "GPIOC23")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC24    PINCTRL_PIN(GPIOC_DAT_BASE + 24, "GPIOC24")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC25    PINCTRL_PIN(GPIOC_DAT_BASE + 25, "GPIOC25")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC26    PINCTRL_PIN(GPIOC_DAT_BASE + 26, "GPIOC26")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC27    PINCTRL_PIN(GPIOC_DAT_BASE + 27, "GPIOC27")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC28    PINCTRL_PIN(GPIOC_DAT_BASE + 28, "GPIOC28")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC29    PINCTRL_PIN(GPIOC_DAT_BASE + 29, "GPIOC29")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC30    PINCTRL_PIN(GPIOC_DAT_BASE + 30, "GPIOC30")
#define OWL2X_PINCTRL_PIN_DAT_GPIOC31    PINCTRL_PIN(GPIOC_DAT_BASE + 31, "GPIOC31")

#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD0    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 0, "GPIOD0")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD1    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 1, "GPIOD1")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD2    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 2, "GPIOD2")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD3    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 3, "GPIOD3")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD4    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 4, "GPIOD4")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD5    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 5, "GPIOD5")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD6    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 6, "GPIOD6")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD7    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 7, "GPIOD7")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD8    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 8, "GPIOD8")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD9    PINCTRL_PIN(GPIOD_OUTPUT_BASE + 9, "GPIOD9")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD10   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 10, "GPIOD10")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD11   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 11, "GPIOD11")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD12   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 12, "GPIOD12")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD13   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 13, "GPIOD13")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD14   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 14, "GPIOD14")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD15   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 15, "GPIOD15")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD16   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 16, "GPIOD16")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD17   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 17, "GPIOD17")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD18   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 18, "GPIOD18")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD19   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 19, "GPIOD19")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD20   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 20, "GPIOD20")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD21   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 21, "GPIOD21")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD22   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 22, "GPIOD22")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD23   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 23, "GPIOD23")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD24   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 24, "GPIOD24")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD25   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 25, "GPIOD25")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD26   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 26, "GPIOD26")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD27   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 27, "GPIOD27")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD28   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 28, "GPIOD28")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD29   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 29, "GPIOD29")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD30   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 30, "GPIOD30")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOD31   PINCTRL_PIN(GPIOD_OUTPUT_BASE + 31, "GPIOD31")

#define OWL2X_PINCTRL_PIN_INPUT_GPIOD0     PINCTRL_PIN(GPIOD_INPUT_BASE + 0, "GPIOD0")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD1     PINCTRL_PIN(GPIOD_INPUT_BASE + 1, "GPIOD1")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD2     PINCTRL_PIN(GPIOD_INPUT_BASE + 2, "GPIOD2")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD3     PINCTRL_PIN(GPIOD_INPUT_BASE + 3, "GPIOD3")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD4     PINCTRL_PIN(GPIOD_INPUT_BASE + 4, "GPIOD4")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD5     PINCTRL_PIN(GPIOD_INPUT_BASE + 5, "GPIOD5")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD6     PINCTRL_PIN(GPIOD_INPUT_BASE + 6, "GPIOD6")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD7     PINCTRL_PIN(GPIOD_INPUT_BASE + 7, "GPIOD7")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD8     PINCTRL_PIN(GPIOD_INPUT_BASE + 8, "GPIOD8")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD9     PINCTRL_PIN(GPIOD_INPUT_BASE + 9, "GPIOD9")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD10    PINCTRL_PIN(GPIOD_INPUT_BASE + 10, "GPIOD10")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD11    PINCTRL_PIN(GPIOD_INPUT_BASE + 11, "GPIOD11")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD12    PINCTRL_PIN(GPIOD_INPUT_BASE + 12, "GPIOD12")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD13    PINCTRL_PIN(GPIOD_INPUT_BASE + 13, "GPIOD13")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD14    PINCTRL_PIN(GPIOD_INPUT_BASE + 14, "GPIOD14")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD15    PINCTRL_PIN(GPIOD_INPUT_BASE + 15, "GPIOD15")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD16    PINCTRL_PIN(GPIOD_INPUT_BASE + 16, "GPIOD16")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD17    PINCTRL_PIN(GPIOD_INPUT_BASE + 17, "GPIOD17")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD18    PINCTRL_PIN(GPIOD_INPUT_BASE + 18, "GPIOD18")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD19    PINCTRL_PIN(GPIOD_INPUT_BASE + 19, "GPIOD19")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD20    PINCTRL_PIN(GPIOD_INPUT_BASE + 20, "GPIOD20")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD21    PINCTRL_PIN(GPIOD_INPUT_BASE + 21, "GPIOD21")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD22    PINCTRL_PIN(GPIOD_INPUT_BASE + 22, "GPIOD22")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD23    PINCTRL_PIN(GPIOD_INPUT_BASE + 23, "GPIOD23")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD24    PINCTRL_PIN(GPIOD_INPUT_BASE + 24, "GPIOD24")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD25    PINCTRL_PIN(GPIOD_INPUT_BASE + 25, "GPIOD25")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD26    PINCTRL_PIN(GPIOD_INPUT_BASE + 26, "GPIOD26")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD27    PINCTRL_PIN(GPIOD_INPUT_BASE + 27, "GPIOD27")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD28    PINCTRL_PIN(GPIOD_INPUT_BASE + 28, "GPIOD28")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD29    PINCTRL_PIN(GPIOD_INPUT_BASE + 29, "GPIOD29")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD30    PINCTRL_PIN(GPIOD_INPUT_BASE + 30, "GPIOD30")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOD31    PINCTRL_PIN(GPIOD_INPUT_BASE + 31, "GPIOD31")

#define OWL2X_PINCTRL_PIN_DAT_GPIOD0     PINCTRL_PIN(GPIOD_DAT_BASE + 0, "GPIOD0")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD1     PINCTRL_PIN(GPIOD_DAT_BASE + 1, "GPIOD1")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD2     PINCTRL_PIN(GPIOD_DAT_BASE + 2, "GPIOD2")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD3     PINCTRL_PIN(GPIOD_DAT_BASE + 3, "GPIOD3")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD4     PINCTRL_PIN(GPIOD_DAT_BASE + 4, "GPIOD4")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD5     PINCTRL_PIN(GPIOD_DAT_BASE + 5, "GPIOD5")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD6     PINCTRL_PIN(GPIOD_DAT_BASE + 6, "GPIOD6")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD7     PINCTRL_PIN(GPIOD_DAT_BASE + 7, "GPIOD7")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD8     PINCTRL_PIN(GPIOD_DAT_BASE + 8, "GPIOD8")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD9     PINCTRL_PIN(GPIOD_DAT_BASE + 9, "GPIOD9")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD10    PINCTRL_PIN(GPIOD_DAT_BASE + 10, "GPIOD10")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD11    PINCTRL_PIN(GPIOD_DAT_BASE + 11, "GPIOD11")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD12    PINCTRL_PIN(GPIOD_DAT_BASE + 12, "GPIOD12")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD13    PINCTRL_PIN(GPIOD_DAT_BASE + 13, "GPIOD13")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD14    PINCTRL_PIN(GPIOD_DAT_BASE + 14, "GPIOD14")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD15    PINCTRL_PIN(GPIOD_DAT_BASE + 15, "GPIOD15")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD16    PINCTRL_PIN(GPIOD_DAT_BASE + 16, "GPIOD16")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD17    PINCTRL_PIN(GPIOD_DAT_BASE + 17, "GPIOD17")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD18    PINCTRL_PIN(GPIOD_DAT_BASE + 18, "GPIOD18")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD19    PINCTRL_PIN(GPIOD_DAT_BASE + 19, "GPIOD19")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD20    PINCTRL_PIN(GPIOD_DAT_BASE + 20, "GPIOD20")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD21    PINCTRL_PIN(GPIOD_DAT_BASE + 21, "GPIOD21")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD22    PINCTRL_PIN(GPIOD_DAT_BASE + 22, "GPIOD22")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD23    PINCTRL_PIN(GPIOD_DAT_BASE + 23, "GPIOD23")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD24    PINCTRL_PIN(GPIOD_DAT_BASE + 24, "GPIOD24")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD25    PINCTRL_PIN(GPIOD_DAT_BASE + 25, "GPIOD25")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD26    PINCTRL_PIN(GPIOD_DAT_BASE + 26, "GPIOD26")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD27    PINCTRL_PIN(GPIOD_DAT_BASE + 27, "GPIOD27")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD28    PINCTRL_PIN(GPIOD_DAT_BASE + 28, "GPIOD28")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD29    PINCTRL_PIN(GPIOD_DAT_BASE + 29, "GPIOD29")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD30    PINCTRL_PIN(GPIOD_DAT_BASE + 30, "GPIOD30")
#define OWL2X_PINCTRL_PIN_DAT_GPIOD31    PINCTRL_PIN(GPIOD_DAT_BASE + 31, "GPIOD31")

#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE0    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 0, "GPIOE0")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE1    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 1, "GPIOE1")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE2    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 2, "GPIOE2")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE3    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 3, "GPIOE3")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE4    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 4, "GPIOE4")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE5    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 5, "GPIOE5")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE6    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 6, "GPIOE6")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE7    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 7, "GPIOE7")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE8    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 8, "GPIOE8")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE9    PINCTRL_PIN(GPIOE_OUTPUT_BASE + 9, "GPIOE9")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE10   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 10, "GPIOE10")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE11   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 11, "GPIOE11")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE12   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 12, "GPIOE12")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE13   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 13, "GPIOE13")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE14   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 14, "GPIOE14")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE15   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 15, "GPIOE15")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE16   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 16, "GPIOE16")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE17   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 17, "GPIOE17")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE18   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 18, "GPIOE18")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE19   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 19, "GPIOE19")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE20   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 20, "GPIOE20")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE21   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 21, "GPIOE21")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE22   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 22, "GPIOE22")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE23   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 23, "GPIOE23")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE24   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 24, "GPIOE24")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE25   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 25, "GPIOE25")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE26   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 26, "GPIOE26")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE27   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 27, "GPIOE27")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE28   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 28, "GPIOE28")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE29   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 29, "GPIOE29")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE30   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 30, "GPIOE30")
#define OWL2X_PINCTRL_PIN_OUTPUT_GPIOE31   PINCTRL_PIN(GPIOE_OUTPUT_BASE + 31, "GPIOE31")

#define OWL2X_PINCTRL_PIN_INPUT_GPIOE0     PINCTRL_PIN(GPIOE_INPUT_BASE + 0, "GPIOE0")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE1     PINCTRL_PIN(GPIOE_INPUT_BASE + 1, "GPIOE1")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE2     PINCTRL_PIN(GPIOE_INPUT_BASE + 2, "GPIOE2")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE3     PINCTRL_PIN(GPIOE_INPUT_BASE + 3, "GPIOE3")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE4     PINCTRL_PIN(GPIOE_INPUT_BASE + 4, "GPIOE4")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE5     PINCTRL_PIN(GPIOE_INPUT_BASE + 5, "GPIOE5")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE6     PINCTRL_PIN(GPIOE_INPUT_BASE + 6, "GPIOE6")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE7     PINCTRL_PIN(GPIOE_INPUT_BASE + 7, "GPIOE7")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE8     PINCTRL_PIN(GPIOE_INPUT_BASE + 8, "GPIOE8")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE9     PINCTRL_PIN(GPIOE_INPUT_BASE + 9, "GPIOE9")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE10    PINCTRL_PIN(GPIOE_INPUT_BASE + 10, "GPIOE10")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE11    PINCTRL_PIN(GPIOE_INPUT_BASE + 11, "GPIOE11")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE12    PINCTRL_PIN(GPIOE_INPUT_BASE + 12, "GPIOE12")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE13    PINCTRL_PIN(GPIOE_INPUT_BASE + 13, "GPIOE13")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE14    PINCTRL_PIN(GPIOE_INPUT_BASE + 14, "GPIOE14")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE15    PINCTRL_PIN(GPIOE_INPUT_BASE + 15, "GPIOE15")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE16    PINCTRL_PIN(GPIOE_INPUT_BASE + 16, "GPIOE16")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE17    PINCTRL_PIN(GPIOE_INPUT_BASE + 17, "GPIOE17")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE18    PINCTRL_PIN(GPIOE_INPUT_BASE + 18, "GPIOE18")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE19    PINCTRL_PIN(GPIOE_INPUT_BASE + 19, "GPIOE19")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE20    PINCTRL_PIN(GPIOE_INPUT_BASE + 20, "GPIOE20")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE21    PINCTRL_PIN(GPIOE_INPUT_BASE + 21, "GPIOE21")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE22    PINCTRL_PIN(GPIOE_INPUT_BASE + 22, "GPIOE22")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE23    PINCTRL_PIN(GPIOE_INPUT_BASE + 23, "GPIOE23")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE24    PINCTRL_PIN(GPIOE_INPUT_BASE + 24, "GPIOE24")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE25    PINCTRL_PIN(GPIOE_INPUT_BASE + 25, "GPIOE25")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE26    PINCTRL_PIN(GPIOE_INPUT_BASE + 26, "GPIOE26")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE27    PINCTRL_PIN(GPIOE_INPUT_BASE + 27, "GPIOE27")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE28    PINCTRL_PIN(GPIOE_INPUT_BASE + 28, "GPIOE28")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE29    PINCTRL_PIN(GPIOE_INPUT_BASE + 29, "GPIOE29")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE30    PINCTRL_PIN(GPIOE_INPUT_BASE + 30, "GPIOE30")
#define OWL2X_PINCTRL_PIN_INPUT_GPIOE31    PINCTRL_PIN(GPIOE_INPUT_BASE + 31, "GPIOE31")

#define OWL2X_PINCTRL_PIN_DAT_GPIOE0     PINCTRL_PIN(GPIOE_DAT_BASE + 0, "GPIOE0")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE1     PINCTRL_PIN(GPIOE_DAT_BASE + 1, "GPIOE1")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE2     PINCTRL_PIN(GPIOE_DAT_BASE + 2, "GPIOE2")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE3     PINCTRL_PIN(GPIOE_DAT_BASE + 3, "GPIOE3")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE4     PINCTRL_PIN(GPIOE_DAT_BASE + 4, "GPIOE4")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE5     PINCTRL_PIN(GPIOE_DAT_BASE + 5, "GPIOE5")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE6     PINCTRL_PIN(GPIOE_DAT_BASE + 6, "GPIOE6")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE7     PINCTRL_PIN(GPIOE_DAT_BASE + 7, "GPIOE7")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE8     PINCTRL_PIN(GPIOE_DAT_BASE + 8, "GPIOE8")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE9     PINCTRL_PIN(GPIOE_DAT_BASE + 9, "GPIOE9")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE10    PINCTRL_PIN(GPIOE_DAT_BASE + 10, "GPIOE10")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE11    PINCTRL_PIN(GPIOE_DAT_BASE + 11, "GPIOE11")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE12    PINCTRL_PIN(GPIOE_DAT_BASE + 12, "GPIOE12")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE13    PINCTRL_PIN(GPIOE_DAT_BASE + 13, "GPIOE13")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE14    PINCTRL_PIN(GPIOE_DAT_BASE + 14, "GPIOE14")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE15    PINCTRL_PIN(GPIOE_DAT_BASE + 15, "GPIOE15")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE16    PINCTRL_PIN(GPIOE_DAT_BASE + 16, "GPIOE16")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE17    PINCTRL_PIN(GPIOE_DAT_BASE + 17, "GPIOE17")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE18    PINCTRL_PIN(GPIOE_DAT_BASE + 18, "GPIOE18")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE19    PINCTRL_PIN(GPIOE_DAT_BASE + 19, "GPIOE19")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE20    PINCTRL_PIN(GPIOE_DAT_BASE + 20, "GPIOE20")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE21    PINCTRL_PIN(GPIOE_DAT_BASE + 21, "GPIOE21")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE22    PINCTRL_PIN(GPIOE_DAT_BASE + 22, "GPIOE22")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE23    PINCTRL_PIN(GPIOE_DAT_BASE + 23, "GPIOE23")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE24    PINCTRL_PIN(GPIOE_DAT_BASE + 24, "GPIOE24")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE25    PINCTRL_PIN(GPIOE_DAT_BASE + 25, "GPIOE25")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE26    PINCTRL_PIN(GPIOE_DAT_BASE + 26, "GPIOE26")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE27    PINCTRL_PIN(GPIOE_DAT_BASE + 27, "GPIOE27")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE28    PINCTRL_PIN(GPIOE_DAT_BASE + 28, "GPIOE28")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE29    PINCTRL_PIN(GPIOE_DAT_BASE + 29, "GPIOE29")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE30    PINCTRL_PIN(GPIOE_DAT_BASE + 30, "GPIOE30")
#define OWL2X_PINCTRL_PIN_DAT_GPIOE31    PINCTRL_PIN(GPIOE_DAT_BASE + 31, "GPIOE31")

#define OWL2X_PIN_NAME_MAX_LEN  5

//#define BANK_MEM_SIZE           0x24
#define OUTPUT_REGS_OFFSET      0x0
#define INPUT_REGS_OFFSET       0x4
#define DATA_REGS_OFFSET        0x8

#define DLEVEL_REGS_OFFSET      0x14
#define PULL_REGS_OFFSET        0x1c

#define PINS_PER_BANK           32
#define PINMUX_PINS_PER_REG        8
#define PINMUX_PINS_BITS           4
#define PINMUX_PINS_MASK           0x0f

#define DATA_PINS_PER_REG       32
#define DATA_PINS_BITS          1
#define DATA_PINS_MASK          0x01

#define DLEVEL_PINS_GPIOER_REG     16
#define DLEVEL_PINS_BITS        2
#define DLEVEL_PINS_MASK        0x03
#define PULL_PINS_GPIOER_REG       16
#define PULL_PINS_BITS          2
#define PULL_PINS_MASK          0x03

#define OWL2X_IRQ_NUMBER        32

#define IRQ_CFG_REG             0x200
#define IRQ_CFG_IRQ_GPIOER_REG             8
#define IRQ_CFG_IRQ_BITS                4
#define IRQ_CFG_IRQ_MASK                ((1 << IRQ_CFG_IRQ_BITS) - 1)
#define IRQ_CTRL_REG            0x210
#define IRQ_CTRL_IRQ_GPIOER_REG            32
#define IRQ_CTRL_IRQ_BITS               1
#define IRQ_CTRL_IRQ_MASK               ((1 << IRQ_CTRL_IRQ_BITS) - 1)
#define IRQ_STATUS_REG          0x214
#define IRQ_STATUS_IRQ_GPIOER_REG          32
#define IRQ_STATUS_IRQ_BITS             1
#define IRQ_STATUS_IRQ_MASK             ((1 << IRQ_STATUS_IRQ_BITS) - 1)

#define IRQ_EDGE_RISING         0x00
#define IRQ_EDGE_FALLING        0x01
#define IRQ_LEVEL_HIGH          0x02
#define IRQ_LEVEL_LOW           0x03
#define IRQ_EDGE_BOTH           0x04

struct owl2x_desc_function {
        const char      *name;
        u8              muxval;
        u8              irqnum;
};

struct owl2x_desc_pin {
        struct pinctrl_pin_desc         pin;
        struct owl2x_desc_function      *functions;
};

struct owl2x_pinctrl_desc {
        const struct owl2x_desc_pin     *pins;
        int                             npins;
        struct pinctrl_gpio_range       *ranges;
        int                             nranges;
};

struct owl2x_pinctrl_function {
        const char      *name;
        const char      **groups;
        unsigned        ngroups;
};

struct owl2x_pinctrl_group {
        const char      *name;
        unsigned long   config;
        unsigned        pin;
};

struct owl2x_pinctrl {
        void __iomem                    *membase;
        struct gpio_chip                *chip;
        struct owl2x_pinctrl_desc       *desc;
        struct device                   *dev;
        struct irq_domain               *domain;
        struct owl2x_pinctrl_function   *functions;
        unsigned                        nfunctions;
        struct owl2x_pinctrl_group      *groups;
        unsigned                        ngroups;
        int                             irq;
        int                             irq_array[OWL2X_IRQ_NUMBER];
        spinlock_t                      lock;
        struct pinctrl_dev              *pctl_dev;
};

#define OWL2X_PIN(_pin, ...)                                    \
        {                                                       \
                .pin = _pin,                                    \
                .functions = (struct owl2x_desc_function[]){    \
                        __VA_ARGS__, { } },                     \
        }

#define OWL2X_FUNCTION(_val, _name)                             \
        {                                                       \
                .name = _name,                                  \
                .muxval = _val,                                 \
        }

#define OWL2X_FUNCTION_IRQ(_val, _irq)                          \
        {                                                       \
                .name = "irq",                                  \
                .muxval = _val,                                 \
                .irqnum = _irq,                                 \
        }

/*
 * The OWL2X PIO registers are organized as is:
 * 0x00 - 0x0c  Muxing values.
 *              8 pins per register, each pin having a 4 bit value
 * 0x10         Pin values
 *              32 bits per register, each pin corresponding to one bit
 * 0x14 - 0x18  Drive level
 *              16 pins GPIOEr register, each pin having a 2bits value
 * 0x1c - 0x20  Pull-Up values
 *              16 pins GPIOEr register, each pin having a 2bits value
 *
 * This is for the first bank. Each bank will have the same layout,
 * with an offset being a multiple of 0x24.
 *
 * The following functions calculate from the pin number the register
 * and the bit offset that we should access.
 */
static inline u32 OWL2X_mux_reg(u16 pin)
{
        u8 bank = pin / PINS_GPIOER_BANK;
        u32 offset = bank * BANK_MEM_SIZE;
        offset += MUX_REGS_OFFSET;
        offset += pin % PINS_GPIOER_BANK / MUX_PINS_GPIOER_REG * 0x04;
        return round_down(offset, 4);
}

static inline u32 OWL2X_mux_offset(u16 pin)
{
        u32 pin_num = pin % MUX_PINS_GPIOER_REG;
        return pin_num * MUX_PINS_BITS;
}

static inline u32 OWL2X_data_reg(u16 pin)
{
        u8 bank = pin / PINS_GPIOER_BANK;
        u32 offset = bank * BANK_MEM_SIZE;
        offset += DATA_REGS_OFFSET;
        offset += pin % PINS_GPIOER_BANK / DATA_PINS_GPIOER_REG * 0x04;
        return round_down(offset, 4);
}

static inline u32 OWL2X_data_offset(u16 pin)
{
        u32 pin_num = pin % DATA_PINS_GPIOER_REG;
        return pin_num * DATA_PINS_BITS;
}

static inline u32 OWL2X_dlevel_reg(u16 pin)
{
        u8 bank = pin / PINS_GPIOER_BANK;
        u32 offset = bank * BANK_MEM_SIZE;
        offset += DLEVEL_REGS_OFFSET;
        offset += pin % PINS_GPIOER_BANK / DLEVEL_PINS_GPIOER_REG * 0x04;
        return round_down(offset, 4);
}

static inline u32 OWL2X_dlevel_offset(u16 pin)
{
        u32 pin_num = pin % DLEVEL_PINS_GPIOER_REG;
        return pin_num * DLEVEL_PINS_BITS;
}

static inline u32 OWL2X_pull_reg(u16 pin)
{
        u8 bank = pin / PINS_GPIOER_BANK;
        u32 offset = bank * BANK_MEM_SIZE;
        offset += PULL_REGS_OFFSET;
        offset += pin % PINS_GPIOER_BANK / PULL_PINS_GPIOER_REG * 0x04;
        return round_down(offset, 4);
}

static inline u32 OWL2X_pull_offset(u16 pin)
{
        u32 pin_num = pin % PULL_PINS_GPIOER_REG;
        return pin_num * PULL_PINS_BITS;
}

static inline u32 OWL2X_irq_cfg_reg(u16 irq)
{
        u8 reg = irq / IRQ_CFG_IRQ_GPIOER_REG * 0x04;
        return reg + IRQ_CFG_REG;
}

static inline u32 OWL2X_irq_cfg_offset(u16 irq)
{
        u32 irq_num = irq % IRQ_CFG_IRQ_GPIOER_REG;
        return irq_num * IRQ_CFG_IRQ_BITS;
}

static inline u32 OWL2X_irq_ctrl_reg(u16 irq)
{
        u8 reg = irq / IRQ_CTRL_IRQ_GPIOER_REG * 0x04;
        return reg + IRQ_CTRL_REG;
}

static inline u32 OWL2X_irq_ctrl_offset(u16 irq)
{
        u32 irq_num = irq % IRQ_CTRL_IRQ_GPIOER_REG;
        return irq_num * IRQ_CTRL_IRQ_BITS;
}

static inline u32 OWL2X_irq_status_reg(u16 irq)
{
        u8 reg = irq / IRQ_STATUS_IRQ_GPIOER_REG * 0x04;
        return reg + IRQ_STATUS_REG;
}

static inline u32 OWL2X_irq_status_offset(u16 irq)
{
        u32 irq_num = irq % IRQ_STATUS_IRQ_GPIOER_REG;
        return irq_num * IRQ_STATUS_IRQ_BITS;
}

#endif /* __PINCTRL_OWL2X_H */
